### ISSUE TITLE
Output bucket name in URL on Circle after deployment

### ISSUE THREAD

**Issue by joannaskao** [ft-interactive/ft-graphics-deploy#2]
Bucket name doesn't get logged along with the rest of the URL on Circle after deployment (it is being deployed to the right place). Since we currently don't have a feedback mechanism to get the URL, it would be nice to be able to find it here.

<img width="1126" alt="screen shot 2017-02-17 at 1 24 15 pm" src="https://cloud.githubusercontent.com/assets/1794257/23077924/8340f0c2-f514-11e6-84c1-3096a0869267.png">

**Comment by callumlocke** [comment]
this is fixed
